### ISSUE TITLE
MANAGE SETTINGS --> Modified ITEMS belonging to each of teh "Add additional element" button

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#281]
Related to #205

The position of individual components in each position has been revised

[Channel_GUI_Additional.elements_v03.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/6152487/Channel_GUI_Additional.elements_v03.txt)

**Comment by strambc** [comment]
https://www.dropbox.com/s/cd8tdp7a3pxcbso/Channel_GUI_Additional.elements_v03.txt?dl=0

**Comment by Akramhar** [comment]
should be done in 0.40
