### ISSUE TITLE
[BUG] MANAGE SETTINGS --> Imported values from image file header are counted as missing upon confirm

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#310]
**Describe the bug**
When loading settings values from the image file header, values are not recognized as such and appear missing upon confirm

**To Reproduce**
1. Manage Settings
2. Load existing Microscope (Lacoste
3. Load existing Image file (Kidney etc.)
4. Values that were loaded are correct but they appear RED when hit confirm.
5. When cut and pasted back in they validate

**Expected behavior**
The values should register as correct and validate

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: v041

**Comment by Akramhar** [comment]
41.2 has a tentative solution for this problem

**Comment by strambc** [comment]
Now it works for float but it does not work anymore for int

![image](https://user-images.githubusercontent.com/4050585/112035238-ba3bfe00-8b15-11eb-9ca0-d36dc8c0a849.png)

**Comment by Akramhar** [comment]
should be done in 0.42, this was a model issue with PositiveInteger in the xsd model not being parsed correctly ("should be a string", instead of should be a number/integer)

**Comment by strambc** [comment]
NOT WORKING
