### ISSUE TITLE
REPOSITORY NAME CHANGE --> MicroMetaApp_React

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#312]
Change the name of this repository to MicroMetaApp-React

Related to 

- https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReactElectron/issues/20
- https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolOmero/issues/16

**Comment by Akramhar** [comment]
done
