### ISSUE TITLE
MANAGE SETTINGS --> Tool tips changes

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#314]
- Open Image file selector --> "Choose the source of the Image file you wish to work with or select 'Skip load image' to continue without an Image". 

- ADD the following NOTE to all the following tooltips --> "NOTE: Any hardware components that are not validated at the current validation Tier, will not be available to add from the available items list. Please either change validation Tier or go back to Manage Instrument to make sure any Hardware Component you wish to manage here is validated at the desired Tier level." 

1. Edit Imaging Environment
2. Edit Microscope Table Settings
3. Edit Objective Settings
4. Edit Sample Positioning Settings
5. ALL BUTTONS IN THE CHANNEL GUI

**Comment by Akramhar** [comment]
should be done in 0.42
