### ISSUE TITLE
[BUG] MANAGE INSTRUMENT--> Menus appear at the top left corner of the app

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#316]
**Describe the bug**
When clicking on a selector menu once the following times menus appear at the top left corner of the app.

**To Reproduce**
1. Happened with Tier selector, Create Mode selector and Save button in both Manage Instrument and Settings

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/112090387-d4073080-8b69-11eb-8b6a-9a2871eecf51.png)

![image](https://user-images.githubusercontent.com/4050585/112090405-dbc6d500-8b69-11eb-93bd-bd86e0fd4512.png)

![image](https://user-images.githubusercontent.com/4050585/112090415-e1bcb600-8b69-11eb-9104-3e5c522604f3.png)

![image](https://user-images.githubusercontent.com/4050585/112091069-11b88900-8b6b-11eb-9910-2099f3eee92a.png)

**Desktop (please complete the following information):**
 - OS Mac
 - Version v042.0

**Additional context**
Might be related to issue #317

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/112105449-cf02ab00-8b82-11eb-8e0d-16fd33ec88c5.png)

**Comment by strambc** [comment]
@Akramhar  Appears to happen upon clicking again on a selector menu that had been already clicked before.
Appears to happen upon clicking again on the same button

**Comment by Akramhar** [comment]
had to roll back a library to avoid this error, should be fixed in 0.42.1
library react-bootstrap 1.5.2 -> rolled back to 1.4.0
