### ISSUE TITLE
[BUG/QUESTION] MANAGE INSTRUMENT --> Menus are different. Is it due to the new libraries?

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#317]
**Describe the issue**
Menus are different and always require scrolling. Is it due to the new libraries?
Is this related to #316 

**To Reproduce**
All menus appear to require scrolling while they did not before.

**OLD BEHAVIOR**
![image](https://user-images.githubusercontent.com/4050585/112090753-89d27f00-8b6a-11eb-937f-e8007326ea6a.png)
![image](https://user-images.githubusercontent.com/4050585/112090783-95be4100-8b6a-11eb-89d1-e91e1e760506.png)

**NEW BEHAVIOR**
![image](https://user-images.githubusercontent.com/4050585/112090859-b38ba600-8b6a-11eb-8ba6-2cfcc2c7e2d7.png)
![image](https://user-images.githubusercontent.com/4050585/112090889-bd150e00-8b6a-11eb-8685-ba65615544b8.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Version v042.0

**Additional context**
Might be related to #316

**Comment by Akramhar** [comment]
this is how they look on windows, now they look the same on mac too.
I'm guessing its because of updated libraries.

**Comment by Akramhar** [comment]
behavior revert to previous due to #316
