### ISSUE TITLE
ALERT MODEL CHANGE --> MirroringDevice, Aperture, FilterCube/OpticsHolderPosition make string and optional

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#321]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Elements name:** MirroringDevice, Aperture, FilterCube <br/>

**Current Field name:** OpticsHolderPosition <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** In some cases it is important to describe the position of these elements rather than just provide a number<br/>

Current Field Data type: positiveInteger <br/>
**New Field Data type: string**

Current Field requirement level: required <br/>
**New Field requirement level: optional**

**Comment by Akramhar** [comment]
should be done in 0.42.1
