### ISSUE TITLE
ALERT MODEL CHANGE --> Lens, Objective/Magnification data type change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#322]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Objective, Lens <br/>

**Current Field name:** Magnification <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** Magnification can be represented by a float. The use of an integer is incorrect. <br/>

Current Field Data type: positiveInteger <br/>
**New Field Data type: float**

**Comment by Akramhar** [comment]
should be done in 0.42.1
