### ISSUE TITLE
ALERT MODEL CHANGE --> MicrolensArray/LensletType changed name to LensletProfileShape, changed description and changed enumeration SimpleType 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#323]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** MicrolensArray <br/>

Current Field name: LensletType <br/>
**New Field name: LensletProfileShape**

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** The term Shape is used more commonly by Manufacturers<br/>

New Field description: This field describes the shape of the profile (e.g., concave vs. convex) of the individual Lenslets that compose this Micro Lens Array.

Current Field enumeration SimpleType name: LensType <br/>
**New Field enumeration SimpleType name: LensShapeType**

**Comment by Akramhar** [comment]
should be done in 0.42.1
