### ISSUE TITLE
ALERT MODEL CHANGE --> Lens/MaterialName description, enumeration SimpleType and list change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#330]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Lens <br/>

**Current Field name:** MaterialName <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** The optical material name was unified to make it the same across Prism, Lens, PolarizationOptics, MirroringDevice and MicrolensArray <br/>

**New Element/Field description:** "This field records the chemical composition or designation of the Material this Lens is made of."

Current Field enumeration SimpleType name: LensMaterialName <br/>
**New Field enumeration SimpleType name: OpticalMaterialName**

**New Field enumeration value(s):** alpha-Barium Borate, Barium Crown (BAK/N-BAK), Barium Flint (BAF/N-BAF), Barium Heavy Flint (BASF/N-BASF), Barium Light Flint (BALF/N-BALF), Borofloat, Boron Crown (BK/N-BK), Calcite, Calcium Fluoride (CaF2), Crown (K/N-K), Crown Flint (KF/N-NK), Crystal Quartz, Dense Crown (SK/N-SK), Dense Flint (SF/N-SF), Extra Dense Crown (SSK/N-SSK), Extra Ligh Flint (LLF), Flint (F/N-F), Fluorine Crown (FK/N-FK), Germanium, Lanthanum Crown (LAK/N-LAK), Lanthanum Dense Flint (LASF/N-LASF), Lanthanum Flint (LAFN/N-LAF), Light Flint (LF), Magnesium Fluoride (MgF2), Phosphate Crown (PK/N-PK), Phosphate Dense (PSK/N-PSK), Polytetrafluoroethylene (PFTE), Rutile (TiO2), Short Flint Special (KZFS/N-KZFS), Silicon (Si), UV-Grade Fused Silica (UVFS), Yttrium Orthovanadate (YVO4), Zerodur (Lithium Aluminum Silicon Oxide), Zinc Crown (ZK/N-ZK), Zinc Selenide (ZnSe), Other

**Comment by Akramhar** [comment]
should be done in 0.42.1
