### ISSUE TITLE
[BUG] MANAGE SETTINGS --> Again Fluorescence LightPath in Channel GUI appears on two lines

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#335]
**Describe the bug**
Again Fluorescence LightPath in Channel GUI appears on two lines

**To Reproduce**
1. Click on EditChannels
2. Click on Edit one channel
3. Fluorescence LightPath appears on two lines

**Expected behavior**
Fluorescence LightPath should all fit on the same line

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/112106175-b6df5b80-8b83-11eb-9eff-5f6a2a842c0f.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: v042.0

**Additional context**
This had been solved before

**Comment by Akramhar** [comment]
I dont seem to be able to reproduce this issue, I added something that may be fixing it in 0.42.1 but I'm not 100% sure
