### ISSUE TITLE
[BUG] MANAGE SETTINGS --> Add Additional Eement(s) button cannot delete element 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#336]
**Describe the bug**
Issue with removing elements from Add Additional Element(s) after entering settings

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/112230833-f6ea2100-8c0b-11eb-8059-d76fff6a29ce.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 042-1

**Comment by Akramhar** [comment]
should be solved in 0.43
