### ISSUE TITLE
MANAGE INSTRUMENT --> Change text in items with multiple transmittance/wavelenght ranges

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#337]
**Is your feature request related to a problem? Please describe.**
The text that appears in the GUI is wrong and unclear.

**Describe the solution you'd like**
New text: " PLEASE NOTE: If the number of WavelengthRange modules or sub-components (e.g., LEDModule) is changed, all values entered but not yet confirmed will be lost" 

before the 

This applies to:

LightSource, 
Prism,
PolarizationOptics
Filter
Dichroic
Lightguide
Detector

**Comment by Akramhar** [comment]
should be solved in 0.44
