### ISSUE TITLE
[FATAL ERROR] MANAGE SETTINGS --> Screen goes blank after hitting Edit Channel

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#338]
**Describe the bug**
Had been working with the app for 2-3 hrs
Working on an existing settings file.
Opened second time and skipping image load

**To Reproduce**
1. Click on Edit Channels
2. Click on Edit selected
 BLANK SCREEN

**Comment by strambc** [comment]
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24994 Download the React DevTools for a better development experience: https://fb.me/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
electron/js2c/renderer_init.js:83 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ electron/js2c/renderer_init.js:83
app.js:582 CleaningFiles from /Users/strambc/MicroMetaApp/schemas
app.js:584 CleaningFiles from /Users/strambc/MicroMetaApp/dimensions
app.js:586 CleaningFiles from /Users/strambc/MicroMetaApp/scripts
app.js:588 CleaningFiles from /Users/strambc/MicroMetaApp/scripts/dependency-jars
app.js:592 CopyFiles from /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/schemas
app.js:597 CopyFiles from /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/dimensions
app.js:602 CopyFiles from /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/scripts
app.js:607 CopyFiles from /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/scripts/dependency-jars
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
microscopeLoader.js:269 Array(1)
28bundle.js:6 enter
canvas.js:885 Object
11bundle.js:6 enter
canvas.js:885 Object
canvas.js:885 Object
2bundle.js:6 enter
canvas.js:885 Object
44bundle.js:6 enter
canvas.js:885 Object
3bundle.js:6 enter
canvas.js:885 Object
11bundle.js:6 enter
canvas.js:885 Object
canvas.js:885 Object
30bundle.js:6 enter
canvas.js:966 deletedID
canvas.js:967 ca7c5c12-c83f-425b-855a-79a7d364ba93
31bundle.js:6 enter
canvas.js:885 Object
11bundle.js:6 enter
canvas.js:885 Object
13bundle.js:6 enter
canvas.js:885 Object
canvas.js:885 Object
49bundle.js:6 enter
canvas.js:885 Object
40bundle.js:6 enter
canvas.js:885 Object
18bundle.js:6 enter
canvas.js:885 Object
canvas.js:885 Object
35bundle.js:6 enter
canvas.js:885 Object
canvas.js:885 Object
4bundle.js:6 enter
canvas.js:885 Object
12bundle.js:6 enter
canvas.js:885 Object
canvas.js:966 deletedID
canvas.js:967 8b6d0433-5b50-4379-9c3e-50a397e6d09a
12bundle.js:6 enter
canvas.js:885 Object
8bundle.js:6 enter
canvas.js:885 Object
bundle.js:6 enter
canvas.js:885 Object
2bundle.js:6 enter
canvas.js:885 Object
5bundle.js:6 enter
canvas.js:885 Object
3bundle.js:6 enter
canvas.js:885 Object
canvas.js:966 deletedID
canvas.js:967 0ac41303-f2b7-4335-8dad-558fd3440268
canvas.js:966 deletedID
canvas.js:967 797f126f-e1b7-4a67-9f28-016dd954c54c
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t (created by Canvas)
    in div (created by Canvas)
printWarning @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88
canvas.js:966 deletedID
canvas.js:967 6648cb63-9224-4e18-b9f3-e24de524ace7
canvas.js:966 deletedID
canvas.js:967 28e8efe3-bbcc-4ae3-a6c6-bf90c76816db
canvas.js:966 deletedID
canvas.js:967 7d4ae1ab-6875-4978-b9b6-4655c3e25b69
canvas.js:966 deletedID
canvas.js:967 3a3ae1e1-1d32-4814-ad67-a0a5742d4e2f
canvas.js:966 deletedID
canvas.js:967 LightEmittingDiodec08f7b68-436c-45ee-a456-1d1701c8dcab
25bundle.js:6 enter
canvas.js:885 Object
canvas.js:966 deletedID
canvas.js:967 LightEmittingDiode20d7b10d-07c9-45bb-b6cb-058971ee9a7c
12bundle.js:6 enter
canvas.js:885 Object
49bundle.js:6 enter
canvas.js:966 deletedID
canvas.js:967 a5fa59c7-a824-44ad-bb09-92ab37e4c907
canvas.js:966 deletedID
canvas.js:967 34231121-6c05-4b30-9e93-7b967ff82154
canvas.js:966 deletedID
canvas.js:967 91640cfa-8a2a-4cb1-a3b4-1ec81f834f29
canvas.js:966 deletedID
canvas.js:967 3d05a2b9-5219-427d-a1f3-09d996c9caf3
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
app.js:1584 IMAGE LOADER
imageLoader.js:154 File
app.js:468 metadataString
app.js:469 {"Image":{"AcquisitionDate":"06/02/2015 @ 15:37:15","Pixels":{"SizeC":3,"Interleaved":"false","PhysicalSizeX":0.16670000666800025,"PhysicalSizeY":0.16670000666800025,"BigEndian":true,"PhysicalSizeZ":0.1,"SignificantBits":16,"DimensionOrder":"XYZCT","SizeT":1,"Type":"uint16","SizeX":502,"SizeZ":100,"SizeY":501},"Channels":[{"SamplesPerPixel":1,"Color":-1.6776961E7,"Name":"405_DAPI"},{"SamplesPerPixel":1,"Color":1.6711935E7,"Name":"491_HIV-1_p24CA"},{"SamplesPerPixel":1,"Color":65535,"Name":"660_Lamin B1"}],"Name":"FSWT-6hVirus-10minFIX-stk_4-EPI.tif"}}

imageLoader.js:114 image
imageLoader.js:115 Object
app.js:1584 IMAGE LOADER
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
app.js:1584 IMAGE LOADER
imageLoader.js:154 File
app.js:468 metadataString
app.js:469 {"Image":{"AcquisitionDate":"06/02/2015 @ 15:37:15","Pixels":{"SizeC":3,"Interleaved":"false","PhysicalSizeX":0.16670000666800025,"PhysicalSizeY":0.16670000666800025,"BigEndian":true,"PhysicalSizeZ":0.1,"SignificantBits":16,"DimensionOrder":"XYZCT","SizeT":1,"Type":"uint16","SizeX":502,"SizeZ":100,"SizeY":501},"Channels":[{"SamplesPerPixel":1,"Color":-1.6776961E7,"Name":"405_DAPI"},{"SamplesPerPixel":1,"Color":1.6711935E7,"Name":"491_HIV-1_p24CA"},{"SamplesPerPixel":1,"Color":65535,"Name":"660_Lamin B1"}],"Name":"FSWT-6hVirus-10minFIX-stk_4-EPI.tif"}}

imageLoader.js:114 image
imageLoader.js:115 Object
app.js:1584 IMAGE LOADER
2app.js:1606 SETTINGS LOADER
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
app.js:1584 IMAGE LOADER
imageLoader.js:154 File
app.js:468 metadataString
app.js:469 {"Image":{"AcquisitionDate":"06/02/2015 @ 15:37:15","Pixels":{"SizeC":3,"Interleaved":"false","PhysicalSizeX":0.16670000666800025,"PhysicalSizeY":0.16670000666800025,"BigEndian":true,"PhysicalSizeZ":0.1,"SignificantBits":16,"DimensionOrder":"XYZCT","SizeT":1,"Type":"uint16","SizeX":502,"SizeZ":100,"SizeY":501},"Channels":[{"SamplesPerPixel":1,"Color":-1.6776961E7,"Name":"405_DAPI"},{"SamplesPerPixel":1,"Color":1.6711935E7,"Name":"491_HIV-1_p24CA"},{"SamplesPerPixel":1,"Color":65535,"Name":"660_Lamin B1"}],"Name":"FSWT-6hVirus-10minFIX-stk_4-EPI.tif"}}

imageLoader.js:114 image
imageLoader.js:115 Object
app.js:1584 IMAGE LOADER
2app.js:1606 SETTINGS LOADER
app.js:1362 setting
app.js:1363 Object
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(6)
microscopeLoader.js:269 Array(1)
2app.js:1584 IMAGE LOADER
4app.js:1606 SETTINGS LOADER
app.js:1017 settings
app.js:1018 Object
app.js:1019 settingName
app.js:1020 AcquisitionSettings_FSWT-6hVirus-10minFIX-stk_4-EPI.tif_faf66ed6-7500-4038-8fb3-8d5fbdd6ad4b
app.js:1040 Array(20)
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88 Warning: Received the string `false` for the boolean attribute `checked`. The browser will interpret it as a truthy value. Did you mean checked={false}?
    in input (created by FormCheckInput)
    in FormCheckInput (created by FormCheck)
    in div (created by FormCheck)
    in FormCheck (created by CheckboxWidget)
    in div (created by FormGroup)
    in FormGroup (created by CheckboxWidget)
    in CheckboxWidget
    in Unknown (created by BooleanField)
    in BooleanField (created by SchemaField)
    in div (created by FormGroup)
    in FormGroup (created by FieldTemplate)
    in FieldTemplate (created by SchemaField)
    in SchemaField (created by ObjectField)
    in div (created by Col)
    in Col (created by ObjectFieldTemplate)
    in div (created by Row)
    in Row (created by ObjectFieldTemplate)
    in div (created by Container)
    in Container (created by ObjectFieldTemplate)
    in ObjectFieldTemplate (created by ObjectField)
    in ObjectField (created by SchemaField)
    in div (created by FormGroup)
    in FormGroup (created by FieldTemplate)
    in FieldTemplate (created by SchemaField)
    in SchemaField (created by Form)
    in form (created by Form)
    in Form (created by ForwardRef)
    in ForwardRef
    in div (created by TabPanel)
    in TabPanel (created by MultiTabFormWithHeaderV3)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by MultiTabFormWithHeaderV3)
    in div (created by TabPanel)
    in TabPanel (created by MultiTabFormWithHeaderV3)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by MultiTabFormWithHeaderV3)
    in div (created by MultiTabFormWithHeaderV3)
    in div (created by ModalWindow)
    in div (created by ModalWindow)
    in ModalWindow (created by MultiTabFormWithHeaderV3)
    in MultiTabFormWithHeaderV3 (created by Footer)
    in Footer (created by MicroMetaAppReact)
    in div (created by MicroMetaAppReactContainer)
    in MicroMetaAppReactContainer (created by MicroMetaAppReact)
    in MicroMetaAppReact (created by MicroMetaAppElectronComponent)
    in MicroMetaAppElectronComponent
printWarning @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88
app.js:1362 setting
app.js:1363 Object
multiTabFormWithHeaderV3.js:71 Uncaught TypeError: Cannot read property 'ID' of undefined
    at _loop (multiTabFormWithHeaderV3.js:71)
    at new MultiTabFormWithHeaderV3 (multiTabFormWithHeaderV3.js:105)
    at constructClassInstance (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12880)
    at updateClassComponent (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17100)
    at beginWork (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:237)
    at invokeGuardedCallback (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:292)
    at beginWork$1 (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23203)
    at performUnitOfWork (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22157)
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19527 The above error occurred in the <MultiTabFormWithHeaderV3> component:
    in MultiTabFormWithHeaderV3 (created by ChannelCanvas_V2)
    in ChannelCanvas_V2 (created by ChannelView)
    in ChannelView (created by SettingMainView)
    in SettingMainView (created by MicroMetaAppReact)
    in div (created by MicroMetaAppReactContainer)
    in MicroMetaAppReactContainer (created by MicroMetaAppReact)
    in MicroMetaAppReact (created by MicroMetaAppElectronComponent)
    in MicroMetaAppElectronComponent

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19527
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11102 Uncaught TypeError: Cannot read property 'ID' of undefined
    at _loop (multiTabFormWithHeaderV3.js:71)
    at new MultiTabFormWithHeaderV3 (multiTabFormWithHeaderV3.js:105)
    at constructClassInstance (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12880)
    at updateClassComponent (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17100)
    at beginWork (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:237)
    at invokeGuardedCallback (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:292)
    at beginWork$1 (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23203)
    at performUnitOfWork (/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22157)
/private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in MicroMetaAppElectronComponent
printWarning @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88
error @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:60
warnAboutUpdateOnUnmountedFiberInDEV @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23161
scheduleUpdateOnFiber @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21169
enqueueSetState @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12639
Component.setState @ /private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:471
onWindowResize @ app.js:311
DevTools failed to load SourceMap: Could not load content for webpack://MicroMetaAppElectron/node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.esm.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack://MicroMetaAppElectron/node_modules/uri-js/dist/es5/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/index.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/file-selector.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/file.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///private/var/folders/lj/w2ftks1j43l52wh5tw9cy5540000gr/T/AppTranslocation/1DE4149E-71CE-493F-887F-CABD01682D54/d/micro-meta-app-electron.app/Contents/Resources/app.asar/public/assets/css/bootstrap.min.css.map:

**Comment by strambc** [comment]
Application had been running continuously for 2-3 hours

**Comment by Akramhar** [comment]
linked to #340, should be fixed in 0.44
