### ISSUE TITLE
[BUG] MANAGE SETTINGS --> When opening an existing Settings file Edit Image Settings button is always RED

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#339]
**Describe the bug**
When opening an existing Settings file Edit Image Settings button is always RED even if the settings in it had been previously confirmed and valdated.

**To Reproduce**
1. Open an existing Settings File in which Edit Image Settings button had been validated.
2. The button appears as red upon entry
3. After entering the button and hitting confirm the button becomes green

**Expected behavior**
Button should be green if prev validated

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac

 - Version 43

**Comment by Akramhar** [comment]
should be solved in 0.44
