### ISSUE TITLE
[BUG] MANAGE SETTINGS --> after creating multiple planes TheZ, TheT and TheC give error "should be integer"

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#341]
**Describe the bug**
after creating multiple planes TheZ, TheT and TheC give validation error "should be integer"

**To Reproduce**

1. Image without imported planes
2. Create multiple plans
3. Entered TheZ, T, and C of Plane 0
4. None of the Planes validate (including Plane 0) 

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/112403174-5156b080-8ce4-11eb-9a33-92fa2e4d1e6a.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 43

**Comment by Akramhar** [comment]
should be solved in 0.44
