### ISSUE TITLE
ALERT MODEL CHANGE --> Lens, Prism, PolarizationOptics, MicrolensArray, MirroringDevice change OpticalMaterialName simple-type enumaration list

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#344]
Propose a change to existing metadata elements or fields/values, e.g. to identify a problem.

Element name(s): Lens, Prism, PolarizationOptics, MicrolensArray, MirroringDevice

Field name(s):  Lesn, Prism, PolarizationOptics/MaterialName  or MirroringDevice, MicrolensArray/SubstrateMaterial (both associated with the OpticalMaterialName enumeration list)

Justification for the addition (brief and compelling):
Missing important optical material names --> Borosilicate and Pyrex

Full description of the proposed addition (enough detail to implement):
Add "Borosilicate" and "Pyrex" to the enumeration list for OpticalMaterialName simple type

**Comment by Akramhar** [comment]
should be solved in 0.45
