### ISSUE TITLE
ALERT MODEL CHANGE --> fixed Repetability -> Repeatability 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#345]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.*

**Current Element name:** SamplePositioningDeviceGroup and SamplePositioningDevice/Stage<br/>

**Current Field name:** ZRepetability, ZRepetabilityUnit, XYRepetability, XYRepetabilityUnit <br/>
New Field name: ZRepeatability, ZRepeatabilityUnit, XYRepeatability, XYRepeatabilityUnit 

**Source of change (e.g., #XXX issue with change request):** 
https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/issues/35

**Brief description of the change and its rationale (short and compelling):**
Fixed typo

**Comment by Akramhar** [comment]
should be solved in 0.45
