### ISSUE TITLE
ALERT MODEL CHANGE --> Fluorophore/Name, Type, ExcitationWavelength, EmissionWavelength REQUIRED --> OPTIONAL - temporary change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#347]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Fluorophore <br/>

**Current Field name:** Name, Type, ExcitationWavelength, EmissionWavelength <br/>

**Source of change:** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** This is a temporary change, that was made necessary by the way in which "Experimental" domain items are implemented in the current version of Micro-MetaApp.  It will be reversed when the next iteration of Micro-Meta App will be released.<br/>

Current Field requirement level: required 
**New Field requirement level: optional**

**Comment by Akramhar** [comment]
should be solved in 0.45
