### ISSUE TITLE
[NEW FEATURE] JSON file --> Add fields to Microscope.json and Settings.json files

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#348]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Add "AppVersion" field to both Microscope and Settings JSON files
- Add "Domain", "Category" and "Extension" fields to all Microscope.JSON file objects

**Additional context**
Requested by Andrea Cosolo (4DN/DCIC) to better handle Micro-Meta App output on the 4DN Data Portal.
https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/issues/27

**Comment by Akramhar** [comment]
should be solved in 0.45
