### ISSUE TITLE
ALERT MODEL CHANGE --> Channel/ImagingMethodTermAccession --> IlluminationTypeTermAccession

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#349]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Channel <br/>

**Current Field name:** ImagingMethodTermAccession <br/>
New Field name: IlluminationTypeTermAccession

**Source of change:** INTERNAL 

**Brief description of the change and its rationale (short and compelling):** IlluminationType and ImagingMethod had mostly overlapping enumeration values. One was removed and the other changed.

**Comment by Akramhar** [comment]
should be solved in 0.45
