### ISSUE TITLE
ALERT MODEL CHANGE --> Channel/ContrastMethod Description and Enumeration value list change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#352]
**Current Element name:** Channel <br/>

**Current Field name:** ContrastMethod<br/>

**Source of change:** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** IlluminationType and ImagingMethod had mostly overlapping enumeration values. One was removed and the other changed.

**New Element/Field description:** "This field describes the technique used to achieve contrast for this Channel."

**New Field enumeration value(s):** 
Brightfield,   Darkfield, Differential Intensity Contrast (DIC), Fluorescence,   HoffmanModulation, ObliqueIllumination, PhaseContrast, PolarizedLight,   VarellContrast, Other

**Comment by Akramhar** [comment]
should be solved in 0.45
