### ISSUE TITLE
[FATAL ERROR] MANAGE SETTINGS --> attempting to load pre 45.3 settings file

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#354]
v45.3

**Describe the bug**
ERROR while attempting to open pre 45.3 Settings file
Same error when attempting to Create Settings from File
Same when loading from file

**To Reproduce**
1. Saved Microscope file with 45.3
2. Attempted to load/open from file pre 45 Settings or attempt to create from scratch

**Comment by Akramhar** [comment]
should be solved in 0.45.4
