### ISSUE TITLE
[FATAL ERROR] MANAGE INSTRUMENT --> load model v01-07 FILE crash

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#358]
[nikon_system_basic_04_.txt](https://github.com/WU-BIMAC/MicroMetaApp-React/files/6249132/nikon_system_basic_04_.txt)

**Describe the bug**
Attempt to load file from December 2020 with version 46-2
File is using OLD v1.07 model

**To Reproduce**
1. Launch
2. Load file from December 2020 from file

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 46-2

**Additional context**

**Comment by Akramhar** [comment]
should be solved in 0.46.3
