### ISSUE TITLE
[BUG] MANAGE SETTINGS --> Change number of Channels --> all channels disappear

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#361]
**Describe the bug**
v46-3 and v46-4
Attempt to ADD new Channel or REMOVE existing Channel --> ALL CHANNELS DISAPPEAR

**To Reproduce**
1. MS, Load Image, edit an existing Settings file or Create from Scratch
2. Edit Channels
3. Remove one of the imported Channels
4. Confirm
5. Edit Channels
6. NO CHANNEL LEFT
7. CHANNELS ARE IN THE JSON FILE

**DOES NOT HAPPEN WHEN AN IMAGE IS NOT LOADED**

**1. Open Mic
2. Skip load image
3. Load existing Setings file or Create from scratch Settings file
THE PROBLEM DOES NOT SHOW UP**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 46-3 and 46-4

**Additional context**
NO ERROR

**Comment by Akramhar** [comment]
should be solved in 0.46.5
