### ISSUE TITLE
Ogg #1 --> lens immersion medium "mineral oil"?

### ISSUE THREAD

**Issue by stephenogg** [WU-BIMAC/MicroMetaApp-React#362]
**Describe the bug**
When creating a new objective lens that is an oil immersion lens, the types of immersion media allowed include "mineral oil" but does not include "immersion oil". I think mineral oil should be removed and immersion oil added.

**To Reproduce**
Create a new lens
Under the "Objective" tab select the popup menu "ImmersionType"

**Expected behavior**
I should be able to select "immersion oil"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - micro-meta-app-electron
 - Version 0.46.5-b1-0

**Additional context**

**Comment by strambc** [comment]
Hi 
this is a request for MODEL CHANGE.
I will close this issue here and move it to the issues list for the model: https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/issues/39
