### ISSUE TITLE
Ogg #3 --> Creating new laser should come with one IlluminationWavelengthRange already active

### ISSUE THREAD

**Issue by stephenogg** [WU-BIMAC/MicroMetaApp-React#364]
**Describe the bug**
When creating a new laser, I enter basic info, then lose it when I realise that the default behaviour is that I must also select the "Add/Remove wavelength range or sub-component" button to add a wavelength range for the laser. Shouldn't creating a new laser have a default of one illuminationwavelengthrange already included?

 - OS: macOS
 - micro-meta-app-electron
 - Version 0.46.5-b1-0 (0.46.5-b1-0)

**Comment by strambc** [comment]
@stephenogg 
I am transferring this issue under MicroscopyMetada4DNGuidelines.
Could you clarify if you would like to have the WavelenghtRange element to be REQUIRED (present by default) at Tier 1 or at a higher Tier?
I am assuming you want Tier 1 but please confirm.
