### ISSUE TITLE
[BUG] MANAGE INSTRUMENT/SETTINGS --> cannot load images

### ISSUE THREAD

**Issue by paulamonterollopis** [WU-BIMAC/MicroMetaApp-React#369]
**Describe the bug**
I am unsure if this is the same bug reported before, but after selecting the Image file to load, it never actually loads. I am unsure if this is the fact that the file is a .nd2 file or something else.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave Version 10.14.6
 - Browser Chrome
 - Version Version 89.0.4389.90 (Official Build) (x86_64)

**Additional context**

**Comment by paulamonterollopis** [comment]
I tested changing the name of the file, changing the format to .tif and loading it from the desktop instead of dropbox. Still it does not allow me to load any image file.

**Comment by Akramhar** [comment]
this was a java version issue, should be solved
