### ISSUE TITLE
ALERT MODEL CHANGE --> Change MicroscopeTable and EnvironmentalControlDevice Category to MicroscopyAccessories

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#371]
**Current Element name:** MicroscopeTable and EnvironmentalControlDevice <br/>

**Source of change:** <br/>
requested in issue https://github.com/WU-BIMAC/NBOMicroscopyMetadataSpecs/issues/43

**Brief description of the change and its rationale (short and compelling):** <br/>
The items in this category, environmental chamber, and table, are not essential, they are accessories

Current Element Category: MicroscopyEssentials
New Element Category: MicroscopyAccessories

**Comment by Akramhar** [comment]
should be solved in version 1.0.0-b1
