### ISSUE TITLE
ALERT MODEL CHANGE --> Plane/ExposureTime MAKE OPTIONAL

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#375]
**THIS IS A TEMPORARY CHANGE UNTIL SOLUTION IS FOUND FOR ISSUE #374** 

**Current Element name:** Plane
**Current Field name:** ExpousureTIme
New Field name: __

**Source of change**
Temporary change related to #374 
Emerged from a conversation with Marco Marcello, Roland Nitschke and Mathias Hammer

**Brief description of the change and its rationale (short and compelling):** 
Currently, if Planes arise from a Confocal Experiment they will remain invalidated as ExposureTime is required but not available. This will have to be fixed permanently by addressing issue #374 
This is a temporary fix.

Current Field requirement level: REQUIRED
**New Field requirement level: OPTIONAL**

**Comment by Akramhar** [comment]
should be fixed in electron 1.0.0-b1-1
