### ISSUE TITLE
ALERT MODEL DOCUMENT ERROR FIX--> Fixed GenericDetectorSettings errors in model docs

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#376]
GenericDetectorSettings was incorrectly handled in the XSD which resulted in a bug reported in issue #372.

Specifically, the 2991 line was corrected to:

<xsd:documentation>Model_Settings=GenericDetectorSettings</xsd:documentation>

This error reflected on errors in the XLS and GRAPHICAL SCHEMA files which were also fixed.

**Comment by Akramhar** [comment]
should be fixed for electron in 1.0.0-b1-1
