### ISSUE TITLE
[FATAL ERROR] MANAGE SETTINGS --> v1-3-2 when importing image file JAVA ERROR

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#401]
**To Reproduce**
1. Select Tier
2. Click on Manage Settings
3. Select Load from home folder
4. Select desired Micrscope.JSON file (TESM)
5. Click continue
6. Select Load image file
7. Select image (FSWT...)
2. ERROR 

![image](https://user-images.githubusercontent.com/4050585/127122334-fab87dc5-2625-4d2c-bf11-4756b4df421c.png)

----
File {name: "FSWT-6hVirus-10minFIX-stk_4-EPI.tif.ome.tif", path: "/Users/strambc/Dropbox/Workstuff/4DN_work_2018_dro…ase 2/FSWT-6hVirus-10minFIX-stk_4-EPI.tif.ome.tif", lastModified: 1611351358000, lastModifiedDate: Fri Jan 22 2021 22:35:58 GMT+0100 (Central European Standard Time), webkitRelativePath: "", …}
app.js:488 Java version validated 1.8.0_281
app.js:501 Uint8Array(561) [123, 34, 73, 109, 97, 103, 101, 34, 58, 123, 34, 65, 99, 113, 117, 105, 115, 105, 116, 105, 111, 110, 68, 97, 116, 101, 34, 58, 34, 48, 54, 47, 48, 50, 47, 50, 48, 49, 53, 32, 64, 32, 49, 53, 58, 51, 55, 58, 49, 53, 34, 44, 34, 80, 105, 120, 101, 108, 115, 34, 58, 123, 34, 83, 105, 122, 101, 67, 34, 58, 51, 44, 34, 73, 110, 116, 101, 114, 108, 101, 97, 118, 101, 100, 34, 58, 102, 97, 108, 115, 101, 44, 34, 80, 104, 121, 115, 105, 99, 97, …]
app.js:514 metadataString
app.js:515 {"Image":{"AcquisitionDate":"06/02/2015 @ 15:37:15","Pixels":{"SizeC":3,"Interleaved":false,"PhysicalSizeX":0.16670000666800025,"PhysicalSizeY":0.16670000666800025,"BigEndian":true,"PhysicalSizeZ":0.1,"SignificantBits":16,"DimensionOrder":"XYZCT","SizeT":1,"SizeX":502,"SizeZ":100,"SizeY":501,"PixelType":"uint16"},"Channels":[{"SamplesPerPixel":1,"Color":-1.6776961E7,"Name":"405_DAPI"},{"SamplesPerPixel":1,"Color":1.6711935E7,"Name":"491_HIV-1_p24CA"},{"SamplesPerPixel":1,"Color":65535,"Name":"660_Lamin B1"}],"Name":"FSWT-6hVirus-10minFIX-stk_4-EPI.tif"}}

imageLoader.js:116 image
imageLoader.js:117 {AcquisitionDate: "06/02/2015 @ 15:37:15", Pixels: {…}, Channels: Array(3), Name: "FSWT-6hVirus-10minFIX-stk_4-EPI.tif"}
app.js:519 error - TypeError - resolve is not a function
app.js:520 stack:
app.js:521 resolve is not a function
app.js:522 TypeError: resolve is not a function
    at MicroMetaAppReact.handleLoadMetadataComplete (app.js:436)
    at ImageLoader.handleLoadMetadataComplete (imageLoader.js:118)
    at MicroMetaAppElectronComponent.onLoadMetadata (app.js:517)
    at eval (imageLoader.js:158)
    at Array.forEach (<anonymous>)
    at ImageLoader.dropzoneDropAccepted (imageLoader.js:155)
    at eval (index.js:699)

**Comment by Akramhar** [comment]
should be solved in 1.3.3
