### ISSUE TITLE
[BUG] MANAGE INSTRUMENT/SETTINGS --> Version 1.7.24 Icon resisezes with mouse over and drag

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#445]
**Describe the bug**
Excitation Filter resizes upon mouse over and upon dragging (see attached video and error)

**To Reproduce**

Use either Version Version 1.7.12 or 1.7.24

Import file 
[hms-wu_lab-vutara_vxl-nettie_20220908_SA.txt](https://github.com/WU-BIMAC/MicroMetaApp-React/files/9679557/hms-wu_lab-vutara_vxl-nettie_20220908_SA.txt)

Ex Filter icon is larger and displays the described behavior when dragged.

**Screenshots**
See attached video

https://user-images.githubusercontent.com/4050585/193157550-c30c099d-2419-4e3e-b2b5-53617d20abea.mov

**Additional context**

/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26244 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
validateModifiers.js:42 Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"
eval @ validateModifiers.js:42
app.js:764 CleaningFiles from /Users/strambc/MicroMetaApp/schemas
app.js:766 CleaningFiles from /Users/strambc/MicroMetaApp/dimensions
app.js:768 CleaningFiles from /Users/strambc/MicroMetaApp/scripts
app.js:770 CleaningFiles from /Users/strambc/MicroMetaApp/scripts/dependency-jars
app.js:772 CleaningFiles from /Users/strambc/MicroMetaApp/scripts/dependency-jars
app.js:774 CleaningFiles from /Users/strambc/MicroMetaApp/tiers
app.js:778 CopyFiles from /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/schemas
app.js:783 CopyFiles from /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/dimensions
app.js:788 CopyFiles from /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/scripts
app.js:793 CopyFiles from /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/scripts/dependency-jars
app.js:798 CopyFiles from /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/tiers
app.js:490 microscopesDB
app.js:491 Object
validateModifiers.js:42 Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"
eval @ validateModifiers.js:42
canvas.js:1649 {"AcquisitionSoftware_d0384b57-8aff-4b19-b8c8-7dec879532f3":{"Name":"SRX","ID":"d0384b57-8aff-4b19-b8c8-7dec879532f3","Tier":1,"Schema_ID":"AcquisitionSoftware.json","ModelVersion":"2.01.1","Extension":"Basic","Domain":"MicroscopeSpecifications","Category":"Software","PositionX":2173.3446,"PositionY":750.76265,"PositionZ":0,"Width":281.0426,"Height":246.6847,"OffsetX":1363.3919677734375,"OffsetY":0,"OccupiedSpot":"Software.AcquisitionSoftware_1","Developer":"Bruker (proprietary)","WebsiteURL":"https://www.bruker.com/en/products-and-solutions/fluorescence-microscopy/super-resolution-microscopes/srx-software.html","Version":"Vutara SRX 7.0.00rc35"},"BeamCollimator_b6956bbf-004c-482d-a400-bc435105d2d0":{"Name":"Lens Assembly for Super-Resolution mode","ID":"b6956bbf-004c-482d-a400-bc435105d2d0","Tier":2,"Schema_ID":"BeamCollimator.json","ModelVersion":"2.01.1","Extension":"Basic","Domain":"MicroscopeHardwareSpecifications","Category":"OpticalAssembly","PositionX":665,"PositionY":769.33,"PositionZ":0,"Width":191.3512,"Height":73,"OffsetX":0,"OffsetY":0,"OccupiedSpot":null,"Description":"Combination of lenses/ 50:50 beamsplitter and mirrors that projects to the biplane detection light path resulting into two individual 50x50 µm focal planes that are 600 nm apart in axial direction. The presence of this item is inferred but detailed information is not available because it is proprietary.","Manufacturer":"Bruker (OEM=proprietary information)","Model":"proprietary information","CatalogNumber":"proprietary information"},"BeamCollimator_d48dd974-1ce0-42f6-b750-715377c95364":{"Name":"Lens Assembly for Diffraction-limited (referred to as Widefield) mode","ID":"d48dd974-1ce0-42f6-b750-715377c95364","Tier":2,"Schema_ID":"BeamCollimator.json","ModelVersion":"2.01.1","Extension":"Basic","Domain":"MicroscopeHardwareSpecifications","Category":"OpticalAssembly","PositionX":905,"PositionY":764.33,"PositionZ":0,"Width":191.3512,"Height":73,"OffsetX":0,"OffsetY":0,"OccupiedSpot":null,"Description":"Combination of lenses that projects to the Diffraction-limited (referred to as Widefield) detection light path resulting into one 200x200 µm FOV. The presence of this item is inferred but detailed information is not available because it is proprietary.","Manufacturer":"Bruker (OEM=proprietary information)","Model":"proprietary information","CatalogNumber":"proprietary information"},"BeamSplitter_1fc15d99-39e7-4597-aaf8-5df2cc18a41a":{"Name":"Biplane 50/50 BS","ID":"1fc15d99-39e7-4597-aaf8-5df2cc18a41a","Tier":2,"Schema_ID":"BeamSplitter.json","ModelVersion":"2.01.1","Extension":"Basic","Domain":"MicroscopeHardwareSpecifications","Category":"MirroringDevice","PositionX":696.29985,"PositionY":899.7351,"PositionZ":1,"Width":70.1611,"Height":56.9366,"OffsetX":6,"OffsetY":400,"OccupiedSpot":"MicroscopeTube_5c5dfa29-0a2f-468a-916b-f39f25e0f1cf_MirroringDevice.BeamSplitter_0","Manufacturer":"Bruker (OEM=proprietary information)","Model":"proprietary information","CatalogNumber":"proprietary information","LotNumber":"proprietary information","SpecsFile":"Information about this item is not available because it is proprietary.","AngleOfIncidenceUnit":"deg","Description":"This 50:50 non-polarizing beamsplitter cube is placed in front of the camera to split the light-path into two branches. The transmitted light reaches the Camera chip directly, while the longer reflected branch is redirected onto a separate area of the Camera chip by a dielectric mirror. Due to the path length difference, the two images on the chip correspond to two sample planes with an axial separation of ~600nm. This enables extraction of the 3D information of a detected fluorescence signal.  (Based on Bi-plane fluorescence microscopy as described in patent: US7880149B2 United States)","Transmittance":0,"Reflectance":0},"CMOS_859c4ef5-35f5-4b2d-af37-09ae495c8124":{"Name":"Orca Fusion BT sCMOS camera","ID":"859c4ef5-35f5-4b2d-af37-09ae495c8124","Tier":1,"Schema_ID":"CMOS.json","ModelVersion":"2.01.1","Extension":"Basic ","Domain":"MicroscopeHardwareSpecifications","Category":"Detector.Camera","PositionX":187.9088,"PositionY":875.1111000000001,"PositionZ":2,"Width":121.83,"Height":122.085,"OffsetX":0,"OffsetY":3.1548819541931152,"OccupiedSpot":"Detector.Camera_1","Current_Number_Of_WavelengthRange":0,"Min_Number_Of_WavelengthRange":0,"Max_Number_Of_WavelengthRange":-1,"Model":"Orca Fusion BT","CatalogNumber":"C15440-20UP","Manufacturer":"Hamamatsu","SpecsFile":"https://www.hamamatsu.com/resources/pdf/sys/SCAS0138E_C14440-20UP_tec.pdf","Mount":"C-mount","ReadNoiseUnit":"e- rms","DarkCurrentRateUnit":"e-/Pixel/sec","DynamicRangeUnit":"decibel (dB)","AmbientOperatingTemperatureUnit":"°C","MaxBitDepth":"16bit","ReadOutNoise":1.6,"PixelWidthUnit":"µm","PixelHeightUnit":"µm","PixelWellCapacityUnit":"e-","MaximumFrameRateUnit":"fps","MaximumReadoutRateUnit":"Pixel per second","VerticalClockSpeedUnit":"µs","ArrayWidth":2304,"ArrayHeight":2304,"PixelWidth":6.5,"PixelHeight":6.5,"Illumin
canvas.js:1650 {}
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220 Warning: Failed prop type: The prop `height` is marked as required in `ResizableBox`, but its value is `null`.
    at ResizableBox (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/ResizableBox.js?:44:35)
    at CanvasElement (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvasElement.js?:52:5)
    at div
    at div
    at span
    at div
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:4906)
    at div
    at div
    at span
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:12475)
    at div
    at Canvas (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvas.js?:66:5)
    at div
    at div
    at MicroMetaAppReactContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:3238:5)
    at MicroMetaAppReact (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:92:5)
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:340:5)
printWarning @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220 Warning: Failed prop type: The prop `width` is marked as required in `ResizableBox`, but its value is `null`.
    at ResizableBox (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/ResizableBox.js?:44:35)
    at CanvasElement (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvasElement.js?:52:5)
    at div
    at div
    at span
    at div
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:4906)
    at div
    at div
    at span
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:12475)
    at div
    at Canvas (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvas.js?:66:5)
    at div
    at div
    at MicroMetaAppReactContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:3238:5)
    at MicroMetaAppReact (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:92:5)
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:340:5)
printWarning @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220 Warning: Failed prop type: The prop `height` is marked as required in `Resizable`, but its value is `null`.
    at Resizable (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/Resizable.js?:40:35)
    at ResizableBox (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/ResizableBox.js?:44:35)
    at CanvasElement (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvasElement.js?:52:5)
    at div
    at div
    at span
    at div
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:4906)
    at div
    at div
    at span
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:12475)
    at div
    at Canvas (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvas.js?:66:5)
    at div
    at div
    at MicroMetaAppReactContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:3238:5)
    at MicroMetaAppReact (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:92:5)
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:340:5)
printWarning @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220 Warning: Failed prop type: The prop `width` is marked as required in `Resizable`, but its value is `null`.
    at Resizable (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/Resizable.js?:40:35)
    at ResizableBox (webpack://MicroMetaAppElectron/./node_modules/react-resizable/build/ResizableBox.js?:44:35)
    at CanvasElement (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvasElement.js?:52:5)
    at div
    at div
    at span
    at div
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:4906)
    at div
    at div
    at span
    at t (webpack://MicroMetaAppElectron/./node_modules/react-drag-drop-container/lib/bundle.js?:6:12475)
    at div
    at Canvas (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/components/canvas.js?:66:5)
    at div
    at div
    at MicroMetaAppReactContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:3238:5)
    at MicroMetaAppReact (webpack://MicroMetaAppElectron/./node_modules/micro-meta-app-react/es/app.js?:92:5)
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:340:5)
printWarning @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:220
DevTools failed to load source map: Could not parse content for file:///Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata%20standard%20+%20software_model%20development/4DN-OME_Micro-Meta-App_devel/Micro-Meta%20App%20Software/react_beta_releases/current%20stable%20release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/public/assets/css/bootstrap.min.css.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.esm.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/@rjsf/core/dist/core.esm.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/uri-js/dist/es5/uri.all.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/file-selector.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for webpack://MicroMetaAppElectron/node_modules/file-selector/dist/es5/file.js.map: Unexpected end of JSON input

**Comment by Akramhar** [comment]
debugged with @strambc, it was a microscope file error.
unknown how the error was produced.
