### ISSUE TITLE
[BUG] MANAGE INSTRUMENT/SETTINGS --> 1.7.24 Error upon hovering over any button

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#446]
Hovering over Manage Instrument, Manage Settings, Tier selection, etc.

Does not happen with 1.17.12

---
validateModifiers.js:42 Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"
eval @ validateModifiers.js:42
eval @ validateModifiers.js:17
validateModifiers @ validateModifiers.js:13
setOptions @ createPopper.js:106
createPopper @ createPopper.js:235
eval @ usePopper.js:165
invokePassiveEffectCreate @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23487
callCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056
flushPassiveEffectsImpl @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23574
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
flushPassiveEffects @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23447
(anonymous) @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23324
workLoop @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:417
flushWork @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:390
performWorkUntilDeadline @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/1.7.24-b1/1.7.24-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:157

**Comment by Akramhar** [comment]
library issue, is going to go away once libraries used update their dependencies.
it doesn't affect application functionalities
